# Generated by Django 6.0.4 on 2026-04-22 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(max_length=500, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Nullable – preserves history if product is deleted', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Show in the landing page featured-products section', verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=280, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, help_text='e.g. Black, Champagne – leave blank for single-SKU', max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, help_text='e.g. XS, S, M, L, XL, 6, 8 – leave blank for single-SKU', max_length=20, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='shippingrule',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='shippingrule',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimum order amount'),
        ),
    ]
